# Generated by Django 4.0.2 on 2022-02-13 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gnome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('Rock', 'Rock'), ('Sky', 'Sky'), ('Forest', 'Forest'), ('Fire', 'Fire'), ('River', 'River')], default='Forest', max_length=6)),
                ('name', models.TextField(max_length=35)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)])),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
    ]
